### ISSUE TITLE
Need Documentation for Help with Contributing

### ISSUE THREAD

**Issue by awitherow** [fernand0aguilar/holisticyouth#8]
What are you trying to build here?

**Comment by frclba** [comment]
Hey
This is a work in progress for something like a landing page.
Thanks again for interacting.  Any help is appreciated. 

Let me know if you need help with anything too.
I've checked your profile and you ship a lot of code. 
That's amazing!



To run this project you can use docker. 
> docker-compose up --build

or yarn
> cd frontend && yarn install && yarn start

access it at
> localhost:3000
